import Link from "next/link";
import { GiftCard } from "../components";
import Layout from "../components/Layout";

const PrivacyPolicy = () => {
  return (
    <Layout title="Shop | Next.js">
      <div className="bg-no-repeat pt-40 overflow-x-hidden   w-[100vw] h-[100%]">
        <div className="xl:px-[120px] bg-white   sm:px-[50px] px-[20px]">
          <div className="mt-9">
            <h6 className="text-[18px]">{`Last updated: April 27, 2021`}</h6>
            <h1 className=" text-[30px] font-semibold lg:text-[50px] text-blue-800 mb-20">
              Privacy Policy
            </h1>
          </div>
          <div className="mb-20 space-y-14">
            <div>
              <h3 className="mb-2 text-[20px] text-blackAlpha-800 font-normal">
                Your privacy is important to us:
              </h3>
              <p className="mb-4 text-[18px] text-blackAlpha-800">
                Therefore, we guarantee that:
              </p>
              <ul className="list-disc ml-7 text-blackAlpha-800">
                <li className="text-[16px] mb-1">
                  We do not rent or sell your personal information to anyone.
                </li>
                <li className="text-[16px] mb-1">
                  Any personal information you provide will be secured by us.
                </li>
                <li className="text-[16px] mb-1">
                  You will be able to erase all the data we have stored on you
                  at any given time. To request data termination, please contact
                  our customer support.
                </li>
              </ul>
            </div>
            <div>
              <h3 className="mb-4 text-[20px] text-blackAlpha-800 font-normal">
                Third-party services:
              </h3>
              <p className="mb-4 text-[16px] text-blackAlpha-800">
                We use third-party services in order to operate our website.
                Please note that these services may contain links to third-party
                apps, websites or services that are not operated by us. We make
                no representation or warranties with regard to and are not
                responsible for the content, functionality, legality, security,
                accuracy, or other aspects of such third-party apps, websites or
                services. Note that, when accessing and/or using these
                third-party services, their own privacy policy may apply.
              </p>
            </div>
            <div>
              <h3 className="mb-4 text-[20px] text-blackAlpha-800 font-normal">
                Google Analytics:
              </h3>
              <p className="mb-4 text-[16px] text-blackAlpha-800">
                This website uses Google Analytics, a web analytics service
                provided by Google, Inc. (“Google”). Google Analytics uses
                “cookies”, which are text files placed on your computer, to help
                the website analyze how users use the site. The information
                generated by the cookie about your use of the website will be
                transmitted to and stored by Google on servers in the United
                States . In case IP-anonymisation is activated on this website,
                your IP address will be truncated within the area of Member
                States of the European Union or other parties to the Agreement
                on the European Economic Area. Only in exceptional cases the
                whole IP address will be first transferred to a Google server in
                the USA and truncated there. The IP-anonymisation is active on
                this website. Google will use this information on behalf of the
                operator of this website for the purpose of evaluating your use
                of the website, compiling reports on website activity for
                website operators and providing them other services relating to
                website activity and internet usage. The IP-address, that your
                Browser conveys within the scope of Google Analytics, will not
                be associated with any other data held by Google. You may refuse
                the use of cookies by selecting the appropriate settings on your
                browser, however please note that if you do this you may not be
                able to use the full functionality of www.coingain.com. You can
                also opt-out from being tracked by Google Analytics with effect
                for the future by downloading and installing Google Analytics
                Opt-out Browser Addon for your current web browser:
                https://tools.google.com/dlpage/gaoptout?hl=en.
              </p>
            </div>
            <div>
              <h3 className="mb-4 text-[20px] text-blackAlpha-800 font-normal">
                Information we collect:
              </h3>
              <p className="mb-4 text-[16px] text-blackAlpha-800">
                Information we collect:
              </p>
              <ul className="list-disc ml-7 text-blackAlpha-800">
                <li className="text-[16px] mb-1">
                  Google ID (to identify you in our database)
                </li>
                <li className="text-[16px] mb-1">Google First & Last name</li>
                <li className="text-[16px] mb-1">Google Email</li>
                <li className="text-[16px] mb-1">Google avatar image</li>
              </ul>
              <p className="mb-4 mt-4 text-[16px] text-blackAlpha-800">
                We do not collect passwords or any other sensitive information.
              </p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default PrivacyPolicy;
