import Layout from "../components/Layout";

const TermsCondition = () => {
  return (
    <Layout title="Shop | Next.js">
      <div className="bg-no-repeat pt-40 overflow-x-hidden   w-[100vw] h-[100%]">
        <div className="xl:px-[120px] bg-white   sm:px-[50px] px-[20px]">
          <div className="mt-9">
            <h6 className="text-[18px]">{`Last updated: April 27, 2021`}</h6>
            <h1 className=" text-[30px] font-semibold lg:text-[50px] text-blue-800 mb-16">
              Terms and Conditions
            </h1>
          </div>
          <div className="mb-20 space-y-14">
            <div>
              <h3 className="mb-2 text-[20px] text-blackAlpha-800 font-normal">
                Terms of Service :
              </h3>
              <p className="mb-4 text-[18px] text-blackAlpha-800">
                Therefore, we guarantee that:
              </p>
              <ul className="list-disc ml-7 text-blackAlpha-800">
                <li className="text-[16px] mb-1">
                  We do not rent or sell your personal information to anyone.
                </li>
                <li className="text-[16px] mb-1">
                  Any personal information you provide will be secured by us.
                </li>
                <li className="text-[16px] mb-1">
                  You will be able to erase all the data we have stored on you
                  at any given time. To request data termination, please contact
                  our customer support.
                </li>
              </ul>
            </div>
            <div>
              <h3 className="mb-4 text-[20px] text-blackAlpha-800 font-normal">
                Third-party services:
              </h3>
              <p className="mb-4 text-[16px] text-blackAlpha-800">
                We use third-party services in order to operate our website.
                Please note that these services may contain links to third-party
                apps, websites or services that are not operated by us. We make
                no representation or warranties with regard to and are not
                responsible for the content, functionality, legality, security,
                accuracy, or other aspects of such third-party apps, websites or
                services. Note that, when accessing and/or using these
                third-party services, their own privacy policy may apply.
              </p>
            </div>
            <div>
              <h3 className="mb-4 text-[20px] text-blackAlpha-800 font-normal">
                Google Analytics:
              </h3>
              <p className="mb-4 text-[16px] text-blackAlpha-800">
                This website uses Google Analytics, a web analytics service
                provided by Google, Inc. (“Google”). Google Analytics uses
                “cookies”, which are text files placed on your computer, to help
                the website analyze how users use the site. The information
                generated by the cookie about your use of the website will be
                transmitted to and stored by Google on servers in the United
                States . In case IP-anonymisation is activated on this website,
                your IP address will be truncated within the area of Member
                States of the European Union or other parties to the Agreement
                on the European Economic Area. Only in exceptional cases the
                whole IP address will be first transferred to a Google server in
                the USA and truncated there. The IP-anonymisation is active on
                this website. Google will use this information on behalf of the
                operator of this website for the purpose of evaluating your use
                of the website, compiling reports on website activity for
                website operators and providing them other services relating to
                website activity and internet usage. The IP-address, that your
                Browser conveys within the scope of Google Analytics, will not
                be associated with any other data held by Google. You may refuse
                the use of cookies by selecting the appropriate settings on your
                browser, however please note that if you do this you may not be
                able to use the full functionality of www.coingain.com. You can
                also opt-out from being tracked by Google Analytics with effect
                for the future by downloading and installing Google Analytics
                Opt-out Browser Addon for your current web browser:
                https://tools.google.com/dlpage/gaoptout?hl=en.
              </p>
            </div>
            <div>
              <h3 className="mb-4 text-[20px] text-blackAlpha-800 font-normal">
                Acceptable use :
              </h3>
              <ul className="list-disc ml-7 text-blackAlpha-800">
                <li className="text-[16px] marker:text-[30px] mb-1">
                  <span>Google ID (to identify you in our database)</span>
                </li>
                <li className="text-[16px] marker:text-[30px] mb-1">
                  <span>Google First & Last name</span>
                </li>
                <li className="text-[16px] marker:text-[30px] mb-1">
                  <span>Google Email</span>
                </li>
                <li className="text-[16px] marker:text-[30px]">
                  <span className="text-[16px]">Google avatar image</span>
                </li>
              </ul>
              <p className="mb-4 mt-4 text-[16px] text-blackAlpha-800">
                We do not collect passwords or any other sensitive information.
              </p>
            </div>
            <div>
              <h3 className="mb-4 text-[20px] text-blackAlpha-800 font-normal">
                Membership :
              </h3>
              <ul className="list-disc ml-7 text-blackAlpha-800">
                <li className="text-[16px] marker:text-[30px] mb-1">
                  <span>
                    Users must be 18 years old and above or 13 years to 18 years
                    old with parental permission. A user between the ages of 13
                    to 18 certifies that a parent has given permission before
                    signing up.
                  </span>
                </li>
                <li className="text-[16px] marker:text-[30px] mb-1">
                  <span>
                    Users must not create more than one account per person, as
                    having multiple accounts may result in all accounts being
                    suspended and all points forfeited
                  </span>
                </li>
                <li className="text-[16px] marker:text-[30px] mb-1">
                  <span>
                    Users must not use a proxy or attempt to mask or reroute
                    their internet connection. That will result in your all
                    accounts being suspended.
                  </span>
                </li>
                <li className="text-[16px] marker:text-[30px]">
                  <span className="text-[16px]">
                    Account balance may not be transferred, exchanged, sold, or
                    otherwise change ownership under any circumstances, except
                    by CoinGain.com
                  </span>
                </li>
                <li className="text-[16px] marker:text-[30px]">
                  <span className="text-[16px]">
                    We reserve the right to close your account, and forfeit any
                    points, if you have violated our terms of service agreement.
                  </span>
                </li>
                <li className="text-[16px] marker:text-[30px]">
                  <span className="text-[16px]">
                    We reserve the right to close your account due to inactivity
                    of 9 or more months. An inactive account is defined as an
                    account that has not earned any gems for 9 or more months
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default TermsCondition;
